import { Genre } from './types';

export const genres: Genre[] = [
  {
    id: 'pop',
    name: 'Pop',
    color: '#ec4899',
    icon: '🎵',
    description: 'Musik populer dengan melodi catchy dan struktur lagu yang mudah diingat. Genre terbesar di dunia dengan artis seperti Taylor Swift, BTS, dan Ed Sheeran.',
    searchTerms: ['pop', 'pop music', 'top hits'],
  },
  {
    id: 'rock',
    name: 'Rock',
    color: '#ef4444',
    icon: '🎸',
    description: 'Musik berkarakter kuat dengan gitar elektrik, bass, dan drum. Dari classic rock hingga alternative, genre ini telah membentuk budaya musik dunia.',
    searchTerms: ['rock', 'rock music', 'alternative rock'],
  },
  {
    id: 'hiphop',
    name: 'Hip-Hop',
    color: '#f59e0b',
    icon: '🎤',
    description: 'Genre yang lahir dari budaya street dengan rap, beat, dan sampling. Artis legendaris seperti Kendrick Lamar, Drake, dan Jay-Z mendominasi chart.',
    searchTerms: ['hip hop', 'rap', 'hip-hop'],
  },
  {
    id: 'rnb',
    name: 'R&B',
    color: '#8b5cf6',
    icon: '💜',
    description: 'Rhythm and Blues menggabungkan soul, funk, dan pop modern. Dikenal dengan vokal yang powerful dan emosional.',
    searchTerms: ['r&b', 'rnb', 'soul', 'rhythm blues'],
  },
  {
    id: 'electronic',
    name: 'Electronic',
    color: '#06b6d4',
    icon: '🎧',
    description: 'Musik yang dibuat dengan synthesizer dan teknologi digital. Dari EDM hingga ambient, genre ini terus berevolusi.',
    searchTerms: ['electronic', 'edm', 'dance', 'techno'],
  },
  {
    id: 'jazz',
    name: 'Jazz',
    color: '#22c55e',
    icon: '🎷',
    description: 'Genre legendaris dengan improvisasi dan harmoni kompleks. Dari swing hingga fusion, jazz adalah seni musik yang mendalam.',
    searchTerms: ['jazz', 'jazz music', 'smooth jazz'],
  },
  {
    id: 'kpop',
    name: 'K-Pop',
    color: '#f472b6',
    icon: '🇰🇷',
    description: 'Phenomena global dari Korea Selatan dengan choreografi memukau dan produksi musik berkualitas tinggi. BTS, BLACKPINK, dan Stray Kids memimpin gelombang Hallyu.',
    searchTerms: ['k-pop', 'kpop', 'korean pop'],
  },
  {
    id: 'latin',
    name: 'Latin',
    color: '#f97316',
    icon: '💃',
    description: 'Musik dengan ritme passion dari Amerika Latin. Reggaeton, salsa, bachata, dan latin pop yang membuat ingin menari.',
    searchTerms: ['latin', 'reggaeton', 'latin pop'],
  },
  {
    id: 'country',
    name: 'Country',
    color: '#a3e635',
    icon: '🤠',
    description: 'Musik akar Amerika dengan cerita tentang kehidupan, cinta, dan alam. Gitar akustik dan violin menjadi ciri khasnya.',
    searchTerms: ['country', 'country music'],
  },
  {
    id: 'classical',
    name: 'Classical',
    color: '#e2e8f0',
    icon: '🎻',
    description: 'Warisan musik orkestra dan komposer legendaris. Dari Mozart hingga modern classical, genre ini menampilkan keindahan musik instrumental.',
    searchTerms: ['classical', 'orchestra', 'symphony'],
  },
  {
    id: 'indie',
    name: 'Indie',
    color: '#14b8a6',
    icon: '🌿',
    description: 'Musik independen dengan karakter unik dan autentik. Artis indie menciptakan suara yang berbeda dari mainstream.',
    searchTerms: ['indie', 'indie rock', 'indie pop', 'alternative'],
  },
  {
    id: 'metal',
    name: 'Metal',
    color: '#78716c',
    icon: '🤘',
    description: 'Musik berat dengan distorsi gitar dan drum yang intens. Dari heavy metal hingga subgenre seperti death metal dan progressive metal.',
    searchTerms: ['metal', 'heavy metal', 'metalcore'],
  },
];

export const musicFacts: string[] = [
  "🎵 Lagu terpendek yang pernah masuk chart adalah 'Stay' oleh Maurice Williams dengan durasi 1:36",
  "🎸 Jimi Hendrix bisa bermain gitar dengan giginya!",
  "🎤 Lagu 'Happy Birthday' baru menjadi domain publik pada 2016",
  "🎧 Spotify memiliki lebih dari 100 juta lagu dalam katalognya",
  "🎹 Piano memiliki 88 tuts - 52 putih dan 36 hitam",
  "🥁 Drum adalah instrumen tertua di dunia, berasal dari 6000 SM",
  "🎻 Stradivarius violin dari tahun 1700-an bernilai jutaan dolar",
  "🎵 Lagu 'Bohemian Rhapsody' oleh Queen tidak memiliki chorus",
  "🎸 Gibson Les Paul pertama dibuat pada tahun 1952",
  "🎤 Whitney Houston's 'I Will Always Love You' memegang rekor note terpanjang di #1",
  "🎧 Musik dapat merangsang produksi dopamine di otak, membuat kita merasa bahagia",
  "🎹 Mozart mulai mengarang musik di usia 5 tahun",
  "🤘 Genre metal terbukti membantu mengurangi stres dan kemarahan",
  "💃 Reggaeton berasal dari Puerto Rico di akhir 1990-an",
  "🇰🇷 K-Pop industry melatih trainee selama 2-5 tahun sebelum debut",
];

export const genreDescriptions: Record<string, string> = {
  pop: 'Pop adalah genre musik populer yang dikenal dengan melodi catchy, struktur lagu yang sederhana (verse-chorus), dan lirik yang relatable. Pop berkembang dari rock & roll di tahun 1950-an dan terus berevolusi. Artis pop modern sering menggabungkan elemen dari genre lain seperti R&B, electronic, dan hip-hop.',
  rock: 'Rock berasal dari rock & roll tahun 1940-50an. Karakteristik utamanya adalah gitar elektrik yang distorsi, bass yang kuat, dan drum yang dinamis. Sub-genre termasuk classic rock, alternative rock, punk rock, dan progressive rock. Band legendaris seperti The Beatles, Led Zeppelin, dan Nirvana mendefinisikan genre ini.',
  hiphop: 'Hip-Hop lahir di Bronx, New York pada 1970-an. Genre ini terdiri dari 4 elemen: MCing (rap), DJing, breakdancing, dan graffiti. Hip-Hop modern telah menjadi salah satu genre paling berpengaruh di dunia, dengan sub-genre seperti trap, drill, dan conscious hip-hop.',
  rnb: 'R&B (Rhythm and Blues) berakar dari musik Afrika-Amerika di tahun 1940-an. Modern R&B menggabungkan elemen pop, soul, funk, dan hip-hop. Dikenal dengan vokal yang emosional, harmoni yang kaya, dan produksi yang polished.',
  electronic: 'Musik Electronic menggunakan instrumen digital dan synthesizer. Genre ini mencakup EDM, house, techno, trance, dubstep, dan ambient. DJ dan producer seperti Daft Punk, Calvin Harris, dan Deadmau5 membawa genre ini ke mainstream.',
  jazz: 'Jazz lahir di New Orleans di akhir abad 19. Karakteristik utamanya adalah improvisasi, swing rhythm, dan harmoni yang kompleks. Sub-genre termasuk bebop, cool jazz, fusion, dan smooth jazz. Legenda seperti Miles Davis dan John Coltrane mendefinisikan genre ini.',
  kpop: 'K-Pop (Korean Pop) adalah genre dari Korea Selatan yang menggabungkan pop, hip-hop, R&B, dan electronic. Dikenal dengan choreografi yang presisi, produksi visual berkualitas tinggi, dan sistem trainee yang ketat. BTS dan BLACKPINK membawa K-Pop ke panggung internasional.',
  latin: 'Musik Latin mencakup berbagai genre dari Amerika Latin dan Spanyol, termasuk reggaeton, salsa, bachata, dan latin pop. Ritme yang passion dan energik menjadi ciri khas genre ini. Bad Bunny, J Balvin, dan Rosalía adalah artis Latin terbesar saat ini.',
  country: 'Country music berakar dari folk music Amerika Selatan. Dikenal dengan storytelling yang kuat, gitar akustik, dan tema tentang kehidupan sehari-hari. Dari classic country seperti Johnny Cash hingga modern country seperti Luke Combs.',
  classical: 'Musik klasik mencakup periode dari Baroque hingga kontemporer. Orkestra, kamar musik, dan opera adalah bentuk utamanya. Komposer legendaris seperti Bach, Mozart, Beethoven, dan Chopin menciptakan karya yang masih dimainkan hingga saat ini.',
  indie: 'Indie (independent) merujuk pada musik yang diproduksi secara independen dari major label. Indie rock, indie pop, dan indie folk adalah sub-genre populer. Dikenal dengan suara yang unik, eksperimental, dan autentik.',
  metal: 'Metal berkembang dari heavy rock di akhir 1960-an. Dikenal dengan distorsi gitar yang berat, tempo cepat, dan vokal yang powerful. Sub-genre termasuk thrash metal, death metal, power metal, dan progressive metal. Black Sabbath dianggap sebagai pelopor genre ini.',
};
